export const ActionTypes = {
  /* CREATE_USER */
  CREATE_USER_START: 'ROBO_RECIPE_GET_LIST_START',
  CREATE_USER_SUCCESS: 'ROBO_RECIPE_GET_LIST_SUCCESS',
  CREATE_USER_ERROR: 'ROBO_RECIPE_GET_LIST_ERROR'
} as const
